# Site settings
title: Sam Huynh
email: samhwang2112.dev@gmail.com
description: >-
  Full Stack Software Developer
avatar: /assets/img/avatar.jpg
resume_file: /assets/files/Resume_SamHuynh.pdf
baseurl: ""
url: ""
github_username: samhwang
linkedin_username: samhwang2112

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-github-metadata

font-awesome:
  assets: true

# Other theme configs for Minimal theme
show_downloads: false
google_analytics:

# Exclude from processing.
# The following items will not be processed, by default.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
