version: 2.1

jobs:
  build-and-test:
    environment:
      DEPLOY_BRANCH: master

    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout

      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      
      - run:
          name: Install dependency
          command: |
            yarn install
            yarn clean
      
      # - save_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ./node_modules

      - run:
          name: Run linting
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test:coverage
      
      - run:
          name: Build Public files
          command: yarn build

      - run:
          name: Set up Git credentials
          command: |
            git config --local user.name "$USER_NAME"
            git config --local user.email "$USER_EMAIL"
      
      - run:
          name: Deploy to GitHub Pages
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
                # yarn deploy
                bash ./.circleci/build.bash
            fi

workflows:
  build-and-test:
    jobs:
      - build-and-test
