name: Generate coveralls

on:
  push:
    branches:
      - develop
    paths:
      - src/**
  pull_request:
    branches:
      - develop
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node 12 and Yarn 1.22
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Set up project
        run: |
          npm -g install yarn
          yarn install
          yarn clean

      - name: Generate test coverage file
        run: yarn test:coverage

      - name: Generate Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}